name = "anxietychat"
main = "./index.js"
compatibility_date = "2025-04-04"

# Make sure we have the Pages asset binding
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./out"

[build]
command = "npm run build"

# Set headers for SPA routing
[[headers]]
for = "/*"
[headers.set]
Cache-Control = "public, max-age=0, must-revalidate" 