name = "anxietychat"
main = "./index.js"
compatibility_date = "2025-04-04"

# Use the Pages preset for proper asset binding
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./out"

[build]
command = "npm run build" 